cart/urls.py
from django.urls import path
from . import views
from .views import cart_view, update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('update-cart/<int:id>/', views.update_cart, name='update_cart'),
]

curtainsandblinds/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    
    if 'cart' not in request.session:
        request.session['cart'] = {}

    cart = request.session['cart']
    product_id = str(product_id)  

    if product_id not in cart:
        cart[product_id] = {'quantity': int(request.POST['quantity']), 'title': product.title, 'price': float(product.price)}
    else:
        cart[product_id]['quantity'] += int(request.POST['quantity'])

    request.session['cart'] = cart
    request.session.modified = True 

    return redirect('cart:cart')

def cart_view(request):
    cart = request.session.get('cart', {})
    products = {id: get_object_or_404(Product, pk=id) for id in cart.keys()}
    return render(request, 'cart/cart.html', {'cart': cart, 'products': products})

def update_cart(request, id):
    if 'cart' not in request.session:
        request.session['cart'] = {}

    if request.method == "POST":
        if request.POST['action'] == 'increase':
            request.session['cart'][str(id)]['quantity'] += 1
        elif request.POST['action'] == 'decrease':

            if request.session['cart'][str(id)]['quantity'] == 1:

                del request.session['cart'][str(id)]
                if len(request.session['cart'])==0:
                    del request.session['cart']
            else:
                request.session['cart'][str(id)]['quantity'] -= 1

        request.session.modified = True

    return redirect('cart:cart')

cart/templates/cart/cart.html
{% load static %}
{% load cart_filters %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping Cart</title>
    <link href="{% static 'main/global.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet"> 
    <link href="{% static 'cart/cart_style.css' %}" rel="stylesheet">`
  </head>
  <body>
    {% include 'main/navbar.html' %}
    <main class="main-holder">
      <div class="container mt-5 mb-4">
        <h1 class="trending-title">Shopping Cart</h1>
        {% if cart %}
            <div class="row card-grid">
                {% for id, item in cart.items %}
                {% with products|get_item:id as product %}
                    <div class="col-lg-2 col-sm-4">
                        <div class="card" id="card-product-{{ id }}">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="card-text">
                                    Quantity: 
                                    <form method="post" action="{% url 'cart:update_cart' id=id %}" class="quantity-form">
                                        {% csrf_token %}
                                        <div class="input-group">
                                            <button type="submit" class="quantity-minus btn btn-outline-secondary" name="action" value="decrease">-</button>
                                            <input type="text" class="form-control" name="quantity" value="{{ item.quantity }}" readonly>
                                            <button type="submit" the "quantity-plus btn btn-outline-secondary" name="action" value="increase">+</button>
                                        </div>
                                    </form>
                                </p>
                                <p class="card-text">Price: ${{ item.price }}</p>
                            </div> 
                        </div>
                    </div>
                {% endwith %}
                {% endfor %}

                <div class="checkout-line"></div>

                <div class="checkout text-center mt-3">
                  {% with cart|cart_total as total %}
                  <h3 class="checkout-subtotal">Subtotal: ${{ total|floatformat:2 }}</h3>
                  {% endwith %}
                  <a href="{% url 'checkout' %}" class="btn btn-success">Checkout</a>
                </div>
                </div>
            </div>
          {% elif not cart %}
            <h2 class="text-center"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Your cart is empty! </h2>
          {% endif %}
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>