cart/urls.py
from django.urls import path
from . import views
from .views import cart_view, update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('update-cart/<int:id>/', views.update_cart, name='update_cart'),
]

curtainsandblinds/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('browse/', views.browse, name='browse'),
    path('product/<int:id>', views.product_detail, name="product_detail"),
    path('', views.home, name='home'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    
]

wishlist/urls.py
from django.urls import path
from . import views
from .views import wishlist_view, add_to_wishlist

app_name = "wishlist"

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('add_to_wishlist/<int:game_id>', add_to_wishlist, name='add_to_wishlist'),
    path('delete/<game_id>/', views.delete_from_wishlist, name='delete_from_wishlist'),
]

products/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Product(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField()
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField()
    trending = models.BooleanField(default=False)
    is_new = models.BooleanField(default=False)
    is_curtain = models.BooleanField(default=False)
    is_blind = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    comment = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Review
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


def browse(request):
    products_list = Product.objects.all() 

    paginator = Paginator(products_list, 18)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'browse.html', {'page_obj': page_obj}) 


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'product_detail.html', {'product': product})

def home(request):
    trending_products = Product.objects.filter(trending=True)
    new_products = Product.objects.filter(is_new=True)
    return render(request, "home.html", {"new_products": new_products})

@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        rating = float(request.POST.get('rating'))
        comment = request.POST.get('comment')
        Review.objects.create(product=product, user=request.user, rating=rating, comment=comment)
    return redirect('products:product_detail', id=product.id)

products/templates/browse.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'main/global.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
    <link href="{% static 'products/browse_style.css' %}" rel="stylesheet">
</head>
<body>
    {% include 'main/navbar.html' %}

    <main class="main-holder">
        <div class="container mt-5 mb-4">
            <h1 class="trending-title">Browse Products</h1>
            <div class="row">
                <div class="col-lg-3 col-sm-12 filter-section">
                    <h5 class="mb-3">Refine your search</h5>

                    <div class="input-group mb-3">
                        <input class="form-control" type="search" placeholder="Search by Title" aria-label="Search">
                    </div>

                    <div class="mb-3">
                        <label for="category-select" class="form-label">Type</label>
                        <select class="form-control" id="category-select">
                            <option selected>All Categories</option>
                            <option value="Curtains">Curtains</option>
                            <option value="Blinds">Blinds</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="developer-select" class="form-label">Developer</label>
                        <select class="form-control" id="developer-select">
                            <option selected>Material</option>
                            <option value="1">Polyester</option>
                            <option value="2">Cotton</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="customRange" class="form-label">Price Range</label>
                        <input type="range" class="form-control-range" id="customRange" min="0" max="100" step="1">
                    </div>
                </div>

                <div class="col-lg-9 col-sm-12 card-grid">
                    <div class="row">
                        {% for product in page_obj %}
                            <div class="col-lg-2 col-sm-4">
                                <a href="/product/{{ product.id }}" style="color:inherit;text-decoration:none">
                                    <div class="card" id="card-product-{{ product.id }}">
                                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ product.title }}</h5>
                                            <p class="card-text">$ {{ product.price }}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            {% if forloop.counter|divisibleby:6 or forloop.last %}
                                </div>
                                {% if not forloop.last %}
                                     <div class="row">
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <nav aria-label="browse pagination">
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

products/templates/product_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'products/game_style.css' %}" rel="stylesheet">
    <link href="{% static 'main/global.css' %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/css/star-rating.min.css" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    {% include 'main/navbar.html' %}
    
    <main class="main-holder">
      <div class="container mt-5 mb-4">
        <h1 class="trending-title">{{ product.title }}</h1>
        <div class="row">
          
          <div class="col-lg-6 col-sm-12 text-center">
            <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.title }}">
          </div>

          <div class="col-lg-6 col-sm-12 card-grid">
            <h2 class="mb-3">{{ product.title }}</h2>
            <p class="mb-3">$ {{ product.price }}</p>

            <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
              {% csrf_token %}
              <div class="form-group">
                <label>Quantity</label>
                <input type="number" min="1" class="form-control" name="quantity" required>
              </div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary">Add to Cart</button>
                <a href="{% url 'wishlist:add_to_wishlist' product.id %}" class="wishlist-button"> 
                    <img src="{% static 'main/images/heart.png' %}" alt="Add to Wishlist" /> 
                </a>
              </div>
            </form>
            
            <h3 class="mb-3">Product Description</h3>
            <p class="mb-3">{{ product.description }}</p>
            
            <h3 class="mb-3">Write a Review</h3>
            <form method="post" action="{% url 'products:add_review' product.id %}">
              {% csrf_token %}
              <textarea name="comment" class="form-control mb-3" placeholder="Write your review here..." required></textarea>
              <div class="form-group">
                <label>Rating</label>
                <input id="rating" name="rating" data-size="xs" class="rating-loading" value="0" required>
              </div>
              <button type="submit" class="btn btn-primary mt-3">Submit Review</button>
            </form>

            <div class="reviews-container">
              <h3 class="mb-3">Reviews</h3>
              {% for review in product.reviews.all %}
                <div class="card mb-3">
                  <div class="card-body">
                  <h5 class="card-title">{{ review.user.username }}</h5>
                  <p class="card-text">{{ review.comment }}</p>
                  <div class="text-right">
                    <small class="text-muted">{{ review.date_added }}</small>
                    <i class="fa fa-star"></i> {{ review.rating }}
                    </div>
                  </div>
                </div>
              {% empty %}
                <p>No reviews yet.</p>
              {% endfor %}
            </div>
        </div>
      </div>
    </main>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/js/star-rating.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function() {
            $("#rating").rating({
                min: 0,
                max: 5,
                step: 0.5,
                size: 'xs',
                showClear: false,
                theme: 'krajee-fa',
                filledStar: '<i class="fa fa-star"></i>',
                emptyStar: '<i class="fa fa-star-o"></i>'
            });
        });
    </script>
</body>
</html>