accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('profile/', views.profile_page, name='profile_page'),
]

cart/urls.py
from django.urls import path
from . import views
from .views import cart_view, update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('update-cart/<int:id>/', views.update_cart, name='update_cart'),
]

curtainsandblinds/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')), 
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wishlist/', include('wishlist.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views


app_name = 'main'

urlpatterns = [
    path('', views.home_page, name = 'home'),
    
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('browse/', views.browse, name='browse'),
    path('product/<int:id>', views.product_detail, name="product_detail"),
    path('', views.home, name='home'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    
]

wishlist/urls.py
from django.urls import path
from . import views
from .views import wishlist_view, add_to_wishlist

app_name = "wishlist"

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('add_to_wishlist/<int:game_id>', add_to_wishlist, name='add_to_wishlist'),
    path('delete/<game_id>/', views.delete_from_wishlist, name='delete_from_wishlist'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from products.models import Product
# Create your views here.


def home_page(request):
    trending_products = Product.objects.filter(trending=True)
    return render(request, 'main/home.html', {'trending_products': trending_products})

main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'main/global.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet"> 
    <link href="{% static 'main/home_style.css' %}" rel="stylesheet">
</head>
<body>
    {% include 'main/navbar.html' %}
    <div class="main-holder">
        <div class="container mt-5">
            <h1 class="trending-title">Trending Products</h1>
        </div>
        
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
            <div class="carousel-inner">
                {% for product in trending_products %}
                {% if forloop.counter|divisibleby:"5" or forloop.first %}
                {% if not forloop.first %}
                </div>
                </div>
                {% endif %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <div class="carousel-container">
                        {% endif %}
                
                        <a href="/product/{{ product.id }}" style="color:inherit;text-decoration:none;"> 
                            <div class="col-md-2 my-1">
                                <div class="card">
                                    <img src="{{ product.image.url }}" alt="{{ product.title }}" class="card-img-top">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ product.title }}</h5>
                                    </div>
                                </div>
                            </div>
                        </a>
                {% endfor %}
                {% if not forloop.last %}
                    </div>
                    </div>
                {% endif %}
            </div>
        
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div> 
    <h2 class="recommended-title">Recommended</h2>

    <div class="gallery-grid">
        <div class="small-images">
            <div class="image-container">
                <a href="/small_img1_link"><img src="{% static 'main/images/smallimage1.jpg' %}" alt="Small img 1" class="small-image"></a>
            </div>
            <div class="image-container">
                <a href="/small_img2_link"><img src="{% static 'main/images/smallimage2.jpg' %}" alt="Small img 2" class="small-image"></a>
            </div>
        </div>
        <div>
          <div class="image-container"></div>
            <a href="/large_img_link"><img src="{% static 'main/images/largeimage.jpg' %}" alt="Large img" class="large-image"></a>
        </div>
        <div>
            <a href="/medium_img_link"><img src="{% static 'main/images/mediumimage.jpg' %}" alt="Medium img" class="medium-image"></a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

main/templates/main/navbar.html
{% load static %}
<link href="{% static 'main/navbar_style.css' %}" rel="stylesheet">


<nav class="navbar navbar-expand-lg fixed-top pt-0 pb-0">
    <a class="navbar-brand pl-3" href="{% url 'main:home' %}">
        <img src="{% static 'main/images/logo.png' %}" width="75" height="75" 
             class="d-inline-block align-top" alt="">
    </a>

   <button class="navbar-toggler" type="button" data-toggle="collapse" 
           data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" 
           aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:browse' %}">Browse</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile_page' %}">Account</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item d-flex align-items-center">
                <a href="{% url 'wishlist:wishlist_view' %}"><img src="{% static 'main/images/wishlist-icon.png' %}" 
                alt="Wishlist" class="icon-image"></a>
            </li>
            <li class="nav-item d-flex align-items-center">
                <a href="{% url 'cart:cart' %}"><img src="{% static 'main/images/cart-icon.png' %}" 
                alt="Cart" class="icon-image icon-image-cart"></a>
            </li>

            {% if request.user.is_authenticated %}
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>